---
name: Python Client - Lint

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:

env:
  DEFAULT_PYTHON: "3.11"

jobs:
  codespell:
    name: ğŸ‘• Codespell
    runs-on: ubuntu-latest
    steps:
      - name: â¤µï¸ Check out code from GitHub
        uses: actions/checkout@v4.1.7
      - name: ğŸ— Set up Poetry
        run: pipx install poetry
        working-directory: client/python
      - name: ğŸ— Set up Python ${{ env.DEFAULT_PYTHON }}
        id: python
        uses: actions/setup-python@v5.1.1
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}
          cache: "poetry"
      - name: ğŸ— Install workflow dependencies
        run: |
          poetry config virtualenvs.create true
          poetry config virtualenvs.in-project true
        working-directory: client/python
      - name: ğŸ— Install Python dependencies
        run: poetry install --no-interaction
        working-directory: client/python
      - name: ğŸš€ Check code for common misspellings
        run: poetry run codespell src/**/*.py
        working-directory: client/python
  ruff:
    name: ğŸ‘• Ruff
    runs-on: ubuntu-latest
    steps:
      - name: â¤µï¸ Check out code from GitHub
        uses: actions/checkout@v4.1.7
      - name: ğŸ— Set up Poetry
        run: pipx install poetry
        working-directory: client/python
      - name: ğŸ— Set up Python ${{ env.DEFAULT_PYTHON }}
        id: python
        uses: actions/setup-python@v5.1.1
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}
          cache: "poetry"
      - name: ğŸ— Install workflow dependencies
        run: |
          poetry config virtualenvs.create true
          poetry config virtualenvs.in-project true
        working-directory: client/python
      - name: ğŸ— Install Python dependencies
        run: poetry install --no-interaction
        working-directory: client/python
      - name: ğŸš€ Run ruff linter
        run: poetry run ruff check --output-format=github .
        working-directory: client/python
      - name: ğŸš€ Run ruff formatter
        run: poetry run ruff format --check .
        working-directory: client/python
  pylint:
    name: ğŸ‘• PyLint
    runs-on: ubuntu-latest
    steps:
      - name: â¤µï¸ Check out code from GitHub
        uses: actions/checkout@v4.1.7
      - name: ğŸ— Set up Poetry
        run: pipx install poetry
        working-directory: client/python
      - name: ğŸ— Set up Python ${{ env.DEFAULT_PYTHON }}
        id: python
        uses: actions/setup-python@v5.1.1
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}
          cache: "poetry"
      - name: ğŸ— Install workflow dependencies
        run: |
          poetry config virtualenvs.create true
          poetry config virtualenvs.in-project true
        working-directory: client/python
      - name: ğŸ— Install Python dependencies
        run: poetry install --no-interaction
        working-directory: client/python
      - name: ğŸš€ Run pylint
        run: poetry run pylint **/*.py
        working-directory: client/python
  mypy:
    name: ğŸ‘• MyPy
    runs-on: ubuntu-latest
    steps:
      - name: â¤µï¸ Check out code from GitHub
        uses: actions/checkout@v4.1.7
      - name: ğŸ— Set up Poetry
        run: pipx install poetry
        working-directory: client/python
      - name: ğŸ— Set up Python ${{ env.DEFAULT_PYTHON }}
        id: python
        uses: actions/setup-python@v5.1.1
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}
          cache: "poetry"
      - name: ğŸ— Install workflow dependencies
        run: |
          poetry config virtualenvs.create true
          poetry config virtualenvs.in-project true
        working-directory: client/python
      - name: ğŸ— Install dependencies
        run: poetry install --no-interaction
        working-directory: client/python
      - name: ğŸš€ Run mypy
        run: poetry run mypy src tests
        working-directory: client/python
